#Uncomment this for Windows development.
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

#Comment this for Windows development.
development:
  adapter: mysql2
  database: rails
  username: root
  password: jaminben
  host: localhost
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  database: rails
  username: root
  password: jaminben
  host: localhost
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  database: rails
  username: root
  password: jaminben
  host: localhost
  socket: /var/lib/mysql/mysql.sock
